# Generated by Django 4.1.1 on 2022-10-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='quality',
            new_name='quantity',
        ),
    ]
